### ISSUE TITLE
Connecting to bbPress issue

### ISSUE THREAD

**Issue by alexandrutasica** [dtbaker/support-hub#10]
Hello dtbaker,
I've tried to connect to bbPress and I got this message:

Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /home/alexdesi/public_html/support/wp-content/plugins/support-hub-0.0.1/vendor/hieu-le/wordpress-xmlrpc-client/src/WordpressClient.php on line 913
Error, the required PHP code has not been added to your bbPress installation. Please check the Support Hub documentation.
You have successfully connected bbPress with the Support Hub plugin. Please click the button below:

Apparently is connected to bbPress but it doesn't detect any forum.

Thank you !

**Comment by dtbaker** [comment]
Hey with bbpress try adding the block of code from this page to the bbpress
WordPress functions.php file http://supporthub.co/documentation/bbpress/

Is the bbpress forum on the same hosting account as supporthub? Working on
a better way to integrate bbpress when it's local like that (that doesn't
involve xmlrpc). But that is a while off.

Thanks for testing!!
