### ISSUE TITLE
Add internal wordpress support

### ISSUE THREAD

**Issue by foxpcteam** [dtbaker/support-hub#13]
Hi,
great plugin, Thanks!

what about add internal wordpress support?

in multisite admins can create tickets for superadmin

in single site, users with some roles can create tickets for admins or support (with support role)

what do you think?

**Comment by dtbaker** [comment]
Yep it's certainly something to consider down the track. 

However initially we will be leaving the complicated "ticket submission" process up to 3rd party systems (like ticksy/zend/ucm/etc..) and only focusing on that sort of integration. Once that is finished though we can certainly look at adding our own ticket submission system. 

Thanks!
