### ISSUE TITLE
vendor/autoload.php error

### ISSUE THREAD

**Issue by wolffe** [dtbaker/support-hub#3]
I'm getting this error:

`Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/ciprian/public_html/demo/wordpress/wp-content/plugins/support-hub/support-hub.php on line 50`

**Comment by andrewdevelopments** [comment]
I've commented the line and it works, but I enter the data(token, appid, session cookie,etc), on Envato Account page I see my template in the bottom of the page, and when I try to reconnect i get this:

> Failed to get account data. Please confirm the envato token is correct as per the help documentation. >Without this you will be unable to post comment replies.
> You have successfully connected Envato with the Support Hub plugin. Please click the button below:

And I get another error from Support Hub Logs: API Error: v2/market/author/sales?page=1 403 /

**Comment by wolffe** [comment]
@wevostudio The exact error is:

`API Error: v2/market/author/sales?page=1 403 / {"error":"access_denied","error_description":"Bearer token not found"}`

**Comment by dtbaker** [comment]
@wolffe thanks for trying this plugin!

If you open the Envato account settings page and click on the "re-load sales data (takes a LONG time)" link does it give any additional information?

does it show ******\* in the token/session/etc.. boxes on that settings page?

**Comment by dtbaker** [comment]
Fixed vendor autoload issue, thanks for reporting :)

**Comment by wolffe** [comment]
I am doing it now. Have you considered integrating it with GitHub updater?

https://github.com/afragen/github-updater

It's very simple, and alpha/beta users would get the latest version whenever you post a new release.

**EDIT:** It times out, I'll try later.

I'm also getting another error, this time using the Query Monitor:

![Query Monitor Screengrab](https://i.gyazo.com/2249de54fa21a8fa486090b2594874b3.png)

**Comment by dtbaker** [comment]
@wolffe thanks for reporting that error. Do you know what version of MySQL is running there? I think there's an error in my "create table" SQL code that only affects certain MySQL versions and I haven't been able to track it down.

**Comment by dtbaker** [comment]
@wolffe adding the github updater tag as well, thanks :)

**Comment by wolffe** [comment]
No problem!

I am using PHP version 5.5.27 and MySQL server version 5.5.42-37.1.
