### ISSUE TITLE
Results but no import

### ISSUE THREAD

**Issue by andrewdevelopments** [dtbaker/support-hub#5]
I get this:
`API Result took :2 seconds and produced 10 results imported 0 new item comments`

And no error logs.

**Comment by dtbaker** [comment]
This is most likely an issue with that database bug reported previously, almost ready with a fix :)

**Comment by andrewdevelopments** [comment]
Alright, awesome job with the plugin !

**Comment by dtbaker** [comment]
Sorry midnight here haven't had a chance to fully test this release on a fresh WP install, but see if that latest update solves a few things :) thanks for testing!
